---
- lineinfile:
    path: /etc/yum.conf
    insertafter: '^[main]'
    line: 'gpgcheck=1'

- lineinfile:
    path: /etc/yum.conf
    insertafter: '^gpgcheck=1'
    line: 'clean_requirements_on_remove=1'

- lineinfile:
    path: /etc/yum.conf
    insertafter: '^clean_requirements_on_remove=1'
    line: 'localpkg_gpgcheck=1'
